#!/usr/bin/env python3
"""Clean local runtime artifacts generated by TrustInspect.

Safe by default: dry-run unless --apply is provided.
This is intended for local developer workspaces, not for deleting source files.
"""
from __future__ import annotations

import argparse
import shutil
from datetime import datetime
from pathlib import Path

RUNTIME_DIRS = ["profiles", "generated_tests", "reports"]


def main() -> int:
    parser = argparse.ArgumentParser(description="Archive or delete TrustInspect runtime artifacts.")
    parser.add_argument("--apply", action="store_true", help="Actually perform changes. Default is dry-run.")
    parser.add_argument("--delete", action="store_true", help="Delete instead of archive. Use only if you are sure.")
    parser.add_argument("--keep-reports", action="store_true", help="Do not move/delete reports/.")
    args = parser.parse_args()

    root = Path.cwd()
    dirs = [d for d in RUNTIME_DIRS if not (args.keep_reports and d == "reports")]
    existing = [root / d for d in dirs if (root / d).exists()]

    if not existing:
        print("[+] No runtime artifact directories found.")
        return 0

    if args.delete:
        for path in existing:
            print(("[apply]" if args.apply else "[dry-run]"), "delete", path)
            if args.apply:
                shutil.rmtree(path, ignore_errors=True)
                path.mkdir(parents=True, exist_ok=True)
        return 0

    stamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    archive = root / "_archive" / "runtime-artifacts" / stamp
    print(("[apply]" if args.apply else "[dry-run]"), "archive root:", archive)
    for path in existing:
        dest = archive / path.name
        print(("[apply]" if args.apply else "[dry-run]"), "move", path, "->", dest)
        if args.apply:
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.exists():
                shutil.rmtree(dest)
            shutil.move(str(path), str(dest))
            path.mkdir(parents=True, exist_ok=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
